module.exports = function(){
	this.thoughtsList = ["It is not how we make mistakes, but how we correct them, that define us. Our mistakes do not define us, they teach us. It is inevitable that we will make mistakes on our journey throughout life, but they do not define us ever.",
	"Success comes to those who have the will power to win over their snooze buttons.",
	"No matter how many times the teeth bite the tongue, still they stay together in the same mouth. That is the spirit of forgiveness.",
	"Positive thinking may not guarantee success, but negative thinking definitely guarantees failure. So always have a positive attitude.",
	"Start by doing what is necessary, then do what is possible, and suddenly you are doing the impossible.",
	"Being happy does not mean everything is perfect, it means you have decided to see beyond the imperfections.",
	"Ships do not sink because of the water around them, ships sink because of the water that gets in them. Do not let what is happening around you get inside you and weigh you down.",
	"Where there is kindness, there is goodness. Where there is goodness, there is magic.",
	"To be kind is more important than to be right. Many times what people need is not a brilliant mind that speaks but a special heart that listens.",
	"Courage does not always roar. Sometimes courage is the quiet voice at the end of the day saying 'I will try again tomorrow.'",
	"We should certainly count our blessings, but we should also make our blessings count.",
	"You can not use up creativity. The more you use, the more you have.",
	"Happiness is not something ready made. It comes from your own actions.",
	"The mirror never loses its ability to reflect even if it is broken into two pieces or thousand pieces. So never change your originality at any situation.",
	"Reality of life, everyone is good to you till you expect nothing from them, and you are too good to them only till you fulfil their expectations.",
	"Whenever you are in conflict with someone, there is one factor that can make the difference between damaging your relationship and deepening it. That factor is attitude.",
	"Remember how far you have come, and you won’t have to rely on a destiny for your future. It will come on your own.",
	"The harder you fall, the heavier your heart; the heavier your heart, the stronger you climb; the stronger you climb, the higher your pedestal.",
	"The purpose of education is to replace an empty mind with an open one.",
	"Personal leadership is the process of keeping your vision and values before you and aligning your life to be congruent with them.",
	"The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy.",
	"Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.",
	"Your mind is a magnet. If you think of blessings, you attract blessings, and if you think of problems, you attract problems. Always cultivate good thoughts and always remain positive & optimistic.",
	"Be positive & think positive, which will improve your inherent intellectual powers.",
	"Hope is one of God's greatest gifts to all of us, because it's the magic that inspires us to keep trying, learning, loving and living.",
	"To be kind is more important than to be right. Many times what people need is not a brilliant mind that speaks but a special heart that listens.",
	"No teacher, no professor nor a mentor can teach the important lessons in life, better than a hungry stomach and an empty pocket.",
	"First comes thought, then organization of that thought into ideas and plans, then transformation of those plans into reality. The beginning, as you will observe, is in your imagination.",
	"The Limitations of man are of his own creation, designed to provide cover for his unwillingness to try.",
	"Begin today. Declare out loud to the universe that you are willing to let go of struggle and eager to learn through joy.",
	"Of course motivation is not permanent. But then neither is bathing;  it is something you should do on a regular basis.",
	"You are never as good as everyone tells you when you win and you are never as bad as they say when you lose."
	];
}